#!/usr/bin/env sh

sed -E 's/(<style-line id="bolt2-cycle.*width=)(".*")(.*)/\1"0.75"\3/g' \
	./bin/vtm-element-default.xml > ./vtm-element-THIN.xml
sed -E 's/(<style-line id="(bolt2|roam2)-cycle.*")(.*)/<!-- \1\3 --!>/g' \
	./bin/vtm-element-default.xml > ./vtm-element-HIDDEN.xml
